version: '3.8'

services:
  airflow:
    build: .
    container_name: airflow_etl
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/app/scripts
    ports:
      - "8080:8080"
    command: standalone

  etl:
    build: .
    container_name: etl_container
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./scripts:/app/scripts
    command: python /app/scripts/script.py


